import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ids = [
  'selected-nav-frame',
  'composer-frame',
  'dialog-frame',
  'menu-frame',
  'panel-frame',
  'primary-button-frame',
]
const names = ['selectedNav', 'composer', 'dialog', 'menu', 'panel', 'primaryButton']
const modes = ['light', 'dark']
const art = Object.fromEntries(modes.map((mode) => [mode, Object.fromEntries(ids.map((id, index) => {
  const bytes = readFileSync(resolve(root, 'assets', 'frames', mode, `${id}.webp`))
  return [names[index], `data:image/webp;base64,${bytes.toString('base64')}`]
}))]))
const source = `/* Generated by scripts/embed-frames.mjs. */\n` +
  `export const FRAME_IDS = ${JSON.stringify(names)} as const\n` +
  `export type FrameId = typeof FRAME_IDS[number]\n` +
  `export type FrameMode = 'light' | 'dark'\n` +
  `export const FRAME_ART = ${JSON.stringify(art)} as const\n`

writeFileSync(resolve(root, 'src', 'client', 'frame-art.generated.ts'), source)
